name: Release messages to discord announcement channel

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Package and release"]
    types:
      - completed

jobs:
  run_main:
    runs-on: ubuntu-18.04
    name: Sends custom message
    steps:
      - name: Sending message
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
